// Generated by https://quicktype.io
//
// how to use
//
// import ConcertJSON from "./ConcertJSON.ts";
//
export interface ConcertJSON {
    type: string;
    id: string;
    name: string;
    date: string;
    open_at: string;
    start_at: string;
    description: string;
    location: string;
    performer: any[];
    setlist: SetlistJSON;
    rates: Rates;
}

export interface Rates {
    value: string;
    state: string;
}

export interface SetlistJSON {
    id: number;
    items: ItemElement[];
    rates: Rates;
}

export interface ItemElement {
    type: string;
    item?: ItemItem;
    memo: string;
}

export interface ItemItem {
    type: string;
    id: string;
    name: string;
}
export default ConcertJSON;
